name: "Linting"

on:
  pull_request:
    branches: [ master ]

jobs:
  golangci:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23


      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
